algorithm: dreamer-v1
operation:
  save: True
  log_dir: mario-bros-2
  device: cpu
  render: True
environment:
  benchmark: mario
  task_name: SuperMarioBros2-v0
  seed: 0
  height: 64
  width: 64
  frame_skip: 1
  pixel_norm: True
parameters:
  dreamer:
    save_path: output/model-low.pt
    train_iterations: 2
    horizon_length: 15
    batch_size: 16
    batch_length: 16
    collect_interval: 1
    num_interaction_episodes: 1
    seed_episodes: 1
    num_evaluate: 1

    kl_divergence_scale: 1
    free_nats: 3
    discount: 0.99
    lambda_: 0.95

    use_continue_flag: False
    actor_learning_rate: 0.0008
    critic_learning_rate: 0.0008
    model_learning_rate: 0.06
    grad_norm_type: 2
    clip_grad: 100

    deterministic_size: 200
    stochastic_size: 30
    stochastic_state_size: 1024
    buffer:
      capacity: 500000

    encoder:
      depth: 32
      stride: 2
      kernel_size: 4

    decoder:
      depth: 32
      stride: 2
      kernel_size: 5

    rssm:
      recurrent_model:
        hidden_size: 200
        activation: ELU

      transition_model:
        hidden_size: 200
        num_layers: 2
        activation: ELU
        min_std: 0.1

      representation_model:
        hidden_size: 200
        num_layers: 2
        activation: ELU
        min_std: 0.1

    reward:
      hidden_size: 400
      num_layers: 2
      activation: ELU

    continue_:
      hidden_size: 400
      num_layers: 3
      activation: ELU

    agent:
      actor:
        hidden_size: 400
        min_std: 0.0001
        init_std: 5.
        mean_scale: 5
        activation: ELU
        num_layers: 2

      critic:
        hidden_size: 400
        activation: ELU
        num_layers: 3
